### ISSUE TITLE
experimental-dispatch url should be @latest instead of @v1

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#128]
Not 100% sure but I think this would make more sense... the latest release is always in use. The only thing I don't know is if `@latest` points to latest released or latest latest, i.e. also the branch generated ones from CI.

@trieloff @tripodsan ?

**Comment by kptdobe** [comment]
https://github.com/adobe/helix-experimental-dispatch/blob/master/.circleci/config.yml#L84 is where the latest is defined: it is in the `semantic-release` job which is run only on `master`. I think then `latest` would be better here.

**Comment by kptdobe** [comment]
Fixed with #129

**Comment by trieloff** [comment]
I'd like to revert this change, as using `@latest` exposes us to the risk of breaking compatibility. When a change is made to `dispatch` that breaks the API, the release of that change will be tagged `@v2` and `@latest`. With `publish` still pointing to `@v1` there would be no problem, as the update to the VCL to match the new API could be done in a branch and iterated upon (the new branch would point to `@v2`)

With `publish` pointing to `@latest`, the API change would get immediate exposure and break the VCL that `publish` is using, potentially bringing down production sites.

**Comment by tripodsan** [comment]
I think, we should do the same as with helix-static, and resolve to the actual latest version during helix-publish, and create a symlink in the users action package to the version used. eg:

```
helix-services/
  static@latest -> static@4.5.6
  static@4.5.6
  experimental-dispatch@latest ->  experimental-dispatch@1.2.3
  experimental-dispatch@1.2.3

1234-12341234/
  helix-static -> static@4.5.6
  dispatch ->  experimental-dispatch@1.2.3
```
