### ISSUE TITLE
Relax some of the cache handling in the VCL

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#137]
This code https://github.com/adobe/helix-publish/blob/master/layouts/fastly/helix.vcl#L1009-L1019 could be done differently in order to give more control to the actions.

If the `beresp` (backend response) contains one of the cache header with any kind of value, do nothing (instead of checking only for the `maxage` case).
`Expires` is unset few lines above, the test is useless: https://github.com/adobe/helix-publish/blob/master/layouts/fastly/helix.vcl#L982. Either remove the test or remove the unset.

cc @trieloff @tripodsan

**Comment by trieloff** [comment]
I think the code changed, so I'm not able to follow the changes you'd like to make.
