### ISSUE TITLE
Add possibility to disable strict https

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-publish#161]
the current `helix.vcl` enforces strict https:

```
  # Force HTTPS
  if (!req.http.Fastly-SSL) {
     error 801 "Force SSL";
  }
```

which is a problem when testing simple sites with custom domains but no TLS termination.
it would be nice to be able to disable this by extension.

**Comment by trieloff** [comment]
I don't think that we should ever support non HTTPS-options, even if it adds considerable overhead for us. Browser support for [plain HTTP is on the way out](https://www.blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/).

**Comment by tripodsan** [comment]
I guess the problem will be to provide the [url challenge](https://letsencrypt.org/docs/challenge-types/) for let's encrypt or [fastly](https://docs.fastly.com/en/guides/domain-validation-for-tls-certificates#url-verification). since there is no certificate yet issued, https is not possible. so the url challenge token will be provided via http.

anyways...this will be a problem only when adding a new domain, and we can open a specific route for this traffic anyways.

---

anyways, during development and testing, it would be good to be able to disable the _force https_

**Comment by trieloff** [comment]
Please also note that we set the HSTS headers to one year, so once HTTPs has been enabled, it effectively cannot be disabled anymore.

**Comment by tripodsan** [comment]
good point.
