### ISSUE TITLE
hlx publish should validate the action path before publishing

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#167]
I've spend the better part of the morning trying to fix a 404 which I could ultimately resolve to a typo in a config file. (At least we got a shiny new `X-Trace` header out of it, which will be useful for further VCL debugging).

We can prevent this by having `hlx publish` validate that the provided OpenWhisk functions actually exist before publishing.

**Comment by MarquiseRosier** [comment]
@trieloff  @tripodsan 

for clarity; publish will need openwhisk credentials if we plan to make it verify actions deployed for strains, as these are deployed under authors namespace

**Comment by MarquiseRosier** [comment]
I was thinking this would best be done in the cli remotePublish.cmd.js file. we can avoid whisk credentials having to be passed into publish service, and it'll be more tolerable, to deal with whatever additional runtime is accrued from filtering whisk to check actions are deployed before a publish, on the cli!

**Comment by tripodsan** [comment]
there are 2 possible cases:
1. the action is public, so it can be accessed via the web url. this is the default case
2. the action is secured, in this case the edge needs to know the wsk secret anyways, which is usually stored in the edge directory during publish. hence the publish action needs to know the secret aswell.

IMO, we should check the action coordinates in helix-publish

**Comment by MarquiseRosier** [comment]
@tripodsan 

For this task; we have to just send a request to the adobeioruntime.net/api/v1/namespaces/{NAMESPACE}/packages/{PACKAGE}

this requires authentication though is there any way to not have to pass these credentials to the service through params? I was thinking to use the edge dictionary 'secrets' like you mentioned @tripodsan but then it's write_only.

**Comment by tripodsan** [comment]
right, I thought that we pass the `wsk_auth` already to the `helix-publish` action, but this is still done int the cli: https://github.com/adobe/helix-cli/blob/7de7b326a19309a3263155e23b132b5bc6a792ae/src/remotepublish.cmd.js#L328

IMO, this is not consistent with the rest of the work that helix-publish does, as it also updates other edge dictionaries. 

@trieloff should we pass the `wsk_auth` to helix-publish and do the entire setup in the action?

**Comment by trieloff** [comment]
Yes, that's probably the right way of doing it.

**Comment by MarquiseRosier** [comment]
Additionally; we have to pass other things like the GitConfig, fastly credentials, and wsk credentials; if we plan to move the publish functionality out of the CLI.
