### ISSUE TITLE
Inconsistent Handling of Algolia Proxy results in error

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#298]
When calling `helix-publish` without an `algoliaappid`, the code below will make sure no Algolia backend is created, which makes some sense, as the Algolia Application ID is encoded in the hostname.

https://github.com/adobe/helix-publish/blob/3326f6f08e5e871bfba183ac8fd57d3b326b7c07/src/fastly/backends.js#L64-L78

However, the code in `helix.vcl` unconditionally sets the `F_Algolia` backend:

https://github.com/adobe/helix-publish/blob/3326f6f08e5e871bfba183ac8fd57d3b326b7c07/layouts/fastly/helix.vcl#L589-L602

This means, the `F_Algolia` backend will be used without being defined, resulting in error messages like [this](https://circleci.com/gh/adobe/helix-pages/1028?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link):

```
error: Error while running the Publish command: FastlyError: Undefined `backend F_Algolia`
at: (input Line 1913 Pos 21)
  set req.backend = F_Algolia;
--------------------#########-
    at request.then (/home/circleci/project/node_modules/@adobe/fastly-native-promises/src/httpclient.js:107:17)
    at process._tickCallback (internal/process/next_tick.js:68:7) { FastlyError: Undefined `backend F_Algolia`
at: (input Line 1913 Pos 21)
  set req.backend = F_Algolia;
--------------------#########-
    at request.then (/home/circleci/project/node_modules/@adobe/fastly-native-promises/src/httpclient.js:107:17)
    at process._tickCallback (internal/process/next_tick.js:68:7) data: { msg: 'Bad request', detail: 'Undefined `backend F_Algolia`\nat: (input Line 1913 Pos 21)\n  set req.backend = F_Algolia;\n--------------------#########-' }, status: 400, code: 'Bad request', name: 'FastlyError' }
Error while running the Publish command
```

This is blocking https://github.com/adobe/helix-pages/pull/148

**Comment by tripodsan** [comment]
@trieloff can we remove the algolia support again until it is clear how to solve the per-project index  configuration? see https://github.com/adobe/helix-cli/pull/1279#issuecomment-578559188

**Comment by trieloff** [comment]
@tripodsan I can see why you'd want to have broader support for additional use cases, but I wouldn't want to remove a feature that is useful and can be used by theblog right now.

**Comment by kptdobe** [comment]
I just stumbled on the `Undefined backend F_Algolia` error and I cannot publish my project...

**Comment by trieloff** [comment]
Fix is incoming in 60…59…58…minutes.
