### ISSUE TITLE
Pass CDN Request ID to OpenWhisk as X-Request-ID

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#305]
I learned from @ddragosd that OpenWhisk honors the `X-Request-ID` request header and replays it in the response. If we take the `X-CDN-Request-ID` and instead pass it as `X-Request-ID`, we will likely be able to trace it though Epsagon with higher consistency (assuming that it will show up as either Activation ID or Transaction ID (@ddragosd to confirm)

@kptdobe FYI

**Comment by kptdobe** [comment]
So what it is the point of keeping `x-cdn-request-id` ? It does not seem we really need it somewhere and we could only use `x-request-id`.

**Comment by tripodsan** [comment]
it would be interresting to have both, and then it is possible to detect if _something_ generates a new`x-request-id` instead of reusing the one received.
