### ISSUE TITLE
X-CDN-Request-ID  pattern typo

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#345]
@trieloff any specific reason why the third block of the `X-CDN-Request-ID` always starts with a 4 ?  See https://github.com/adobe/helix-publish/blob/master/layouts/fastly/helix.vcl#L137
There is a `"-4"`. This looks like a typo and I assume should be a `"-"`.

I can fix it together with https://github.com/adobe/helix-publish/issues/344.

**Comment by trieloff** [comment]
Just a typo.
