### ISSUE TITLE
Fastly write limit: revisit our publish process

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#35]
With the developer site, we recently hit the Fastly write limit.

Error you get is: `You have exceeded your hourly rate limit. Please contact support@fastly.com if you think this is a mistake.`

```
error: - Set content repo429 - {"msg":"You have exceeded your hourly rate limit. Please contact support@fastly.com if you think this is a mistake."}
error: Error while running the Publish command: Error: Error setting edge dictionary value
    at job.putDict.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/publish.cmd.js:677:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)Error setting edge dictionary value
Error while running the Publish command
Exited with code 1
```

After discussion with @ejthurgo on their dedicated Adobe slack channel, here are some data:

* Fastly default: 1000 writes (PUT, POST, PATCH, DELETE) per hour
* Extending it to more than 10k would require Fastly engineering
* Naturally first step would be to improve our code to reduce the number of writes
* Each API call returns the `fastly-ratelimit-remaining` response header
* Rate limit is per API token (TODO to be confirmed)

I did some measures in the https://github.com/adobe/developer.adobe.com site. As of current state:
* helix-config contains 15 strains
* during one single `hlx publish`, `fastly-ratelimit-remaining` goes from 998 to 794!
* 204 writes which means an average of 13 writes per strain
* this means the current developer site can be published 4 times per hour only.

Improving the limit to 10k is probably the first easy step to allow use to deploy up to 49 times per hour but that's not a sustainable and long term solution: we need to review and improve our code to optimise the number of writes.

**Comment by trieloff** [comment]
Stale.
