### ISSUE TITLE
url conditions are not backward compatible

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-publish#372]
**Description**
using a helix-config.yaml with implizit url conditions doesn't generate the correct VCL.
Since the same still works in simulator, it is a bit confusing.

see https://github.com/adobe/project-helix.io/issues/69

### Suggestion
Drop implicit URL support completely.

**Comment by dominique-pfister** [comment]
Thanks for spotting that, @tripodsan , the fallback for `strain.url` was inadvertently removed in `helix-publish`.

**Comment by tripodsan** [comment]
as I said, I would drop the legacy support as we don't have any projects anymore that need it.

@trieloff WDYT?

**Comment by dominique-pfister** [comment]
OK, but if we don't support `url` or `urls` in a strain in `helix-publish` anymore, couldn't we also remove that support entirely in `helix-shared`, as its version has already been bumped >= 6.0.0?

**Comment by dominique-pfister** [comment]
see https://github.com/adobe/helix-shared/issues/269
