### ISSUE TITLE
VCL should propagate more specific errors 

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-publish#378]
**Is your feature request related to a problem? Please describe.**
The Helix VCL currently handles and propagates `404`s from the origin and masks all other errors as `500`.

**Describe the solution you'd like**
The VCL should propagate specific errors, such as `403`, `503`, `504` (and probably others).

**Additional context**
https://github.com/adobe/helix-pages/issues/218

**Comment by stefan-guggisberg** [comment]
The relevant code: https://github.com/adobe/helix-publish/blob/4319fe9e65545c3acdc9aba9c3ab0758ebff1195/layouts/fastly/helix.vcl#L834-L838

**Comment by trieloff** [comment]
@kptdobe you might want to make use of https://github.com/adobe/helix-publish/pull/379
