### ISSUE TITLE
Protect X-Debug header with a key

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#38]
Agree. Storing it in a dictionary is just an extra step that we don't need to take.

I'd always print the debug key, but allow setting it with `--debug-key=hunter2`

_Originally posted by @trieloff in https://github.com/adobe/helix-cli/issues/264#issuecomment-430579963_

**Comment by trieloff** [comment]
I think we could simply use the service config ID, which is well-known to the developer, but not otherwise shared. @davidnuescheler what do you think?

**Comment by kptdobe** [comment]
I am going to take a look at this with @MarquiseRosier to explore with him this part of the stack.
