### ISSUE TITLE
VCL trace returned via X-Trace header is incomplete

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-publish#383]
**Is your feature request related to a problem? Please describe.**
The vcl trace information returned in the `X-Trace` debug response header seems to be incomplete/inconsistent. 

**Describe the solution you'd like**
Investigate the different vcl flow patterns (on edge node vs shield nodes) and fix the respective trace statements.

**Additional context**
Relates to older issue: #97

**Comment by trieloff** [comment]
I think the issue that @kptdobe discovered in #382 is that the trace isn't passed through for synthetic responses. Arguably, for these error pages it is especially useful to have the traces.
