### ISSUE TITLE
Turn on Extra Logging when X-Debug is set

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#403]
From @mcorlan:

> - By default, successful blocking invocations will not produce an activation record, thus running "wsk activation list" will not list any of these. Logs are still recorded and can be retrieved using the activation ID  - this is still being sent to the client invoking the action
> - Developers can force creating an activation record for successful blocking invocations by including this header `X-OW-EXTRA-LOGGING: on` in the request

We should turn on this level of extra logging when `X-Debug` is set.

**Comment by rofe** [comment]
@trieloff all our monitors are now getting 404s on the 2nd request to retrieve the activation record. We should either implement [this](#403) or [that](https://github.com/adobe/helix-ops/issues/63).

**Comment by trieloff** [comment]
I don't think we need to implement #403, as the status requests from new relic don't go through Fastly. Just adding the `X-OW-EXTRA-LOGGING: on` header in the New Relic test script should be enough.
