### ISSUE TITLE
Package check does not work

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#416]
Unless you deploy to the `helix` namespace, which you shouldn't do.

**Comment by trieloff** [comment]
Me on Slack:

> The helix-publish package check is not working if your pipeline actions are not in the helix namespace.
11:57
> `helix-cli` has the helix namespace hardcoded in the `--publish-api` URL, so it can’t pick up the credentials from a bound package.
11:59
> So we either need to change `helix-cli` to pass on the OW credentials or change `helix-cli` to replace helix in the `--publish-api` URL with the `--wsk-namespace`  parameter
12:00
> (or take the namespace from the `helix-config.yaml`)
12:00
> We also need to think about what happens when you are using multiple namespaces in a single config.

Me in another thread on Slack:

> Could you create a quick PR to disable the publish check (maybe just a warning)

**Comment by tripodsan** [comment]
@MarquiseRosier @trieloff can you create a follow up issue to enable it again and fix it in helix-cli ?

**Comment by tripodsan** [comment]
I created https://github.com/adobe/helix-cli/issues/1388
