### ISSUE TITLE
Font files keep firing 503

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#422]
Many current incidents are related to `/hlx_fonts`.

I was lucky to catch one in my browser (just opened https://theblog-adobe.hlx.page/hlx_fonts/af/ff86c5/00000000000000003b9b3f87/27/d?primer=5f85f9f11cd5381b63b5247f08def02e63540b6c5567c66a734e1faa3ac86970&fvd=n5&v=3):

```
Error 503 hostname doesn't match against certificate
hostname doesn't match against certificate

Guru Mediation:
Details: cache-cdg20737-CDG 1588007841 3210961208

Varnish cache server
```

A reload few seconds later gave me a positive response.

cc @trieloff does this ring a bell ?

**Comment by trieloff** [comment]
Suggested fix: we disable the SSL validation for the Fonts backend.

**Comment by dominique-pfister** [comment]
Thanks, @trieloff , disabled manually in version [288](https://manage.fastly.com/configure/services/1McGRQOYFuABWBHyD8D4Ux/versions/288/origins) of our configuration.

Shall I also disable it in the GH repo, so it survives another deployment?

**Comment by trieloff** [comment]
Yes, that would be ideal.
