### ISSUE TITLE
Static Requests don't work (post-refactor)

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#45]
Follow-up to #42 see https://www.primordialsoup.life/css/bulma.css

```http
GET /css/bulma.css HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: www.primordialsoup.life
User-Agent: HTTPie/1.0.2
X-Debug: true

HTTP/1.1 503 Service Unavailable
Accept-Ranges: bytes
Connection: close
Content-Length: 452
Content-Type: text/html; charset=utf-8
Date: Fri, 15 Mar 2019 09:28:47 GMT
Retry-After: 0
Server: Varnish
Strict-Transport-Security: max-age=31536000
Via: 1.1 varnish
X-Action-Root: trieloff/32b8642c4c1399c7a779ebaa130a3eba1cb53092
X-Backend-URL: /api/v1/web/trieloff/32b8642c4c1399c7a779ebaa130a3eba1cb53092/css?owner=trieloff&repo=helix-demo&ref=master&path=/css/bulma.md&selector=&extension=css&strain=default&rootPath=&params=
X-Cache: MISS
X-Cache-Hits: 0
X-FullDirname: /css
X-Github-Static-Ref: @
X-Orig-URL: /css/bulma.css
X-Repo-Root-Path:
X-Request-Type: Dynamic
X-Served-By: cache-fra19121-FRA
X-Strain: default
X-Timer: S1552642127.146770,VS0,VE414
X-Trace: vcl_recv; hlx_recv_init; hlx_strain(resolved); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(none); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static; RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_static; hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static; RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static; RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_static; hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static; RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_error; hlx_error_errors; vcl_deliver; hlx_headers_deliver
X-URL: /css/bulma.css
X-Version: 1060; src=1060; cli=1.0.0; rev=online; src=1060; cli=1.0.0; rev=online; src=1060; cli=1.0.0; rev=online; src=1060; cli=1.0.0; rev=online; src=1060; cli=1.0.0; rev=online

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Service Unavailable</title>
  </head>
  <body>
    <h1>Error 503 Service Unavailable</h1>
    <p>Service Unavailable</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-fra19121-FRA 1552642128 1335122751</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by trieloff** [comment]
First clue: `X-Trace` is telling us that something is going very wrong here. It's long, so let's break it down:

1.`vcl_recv; hlx_recv_init; hlx_strain(resolved); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(none); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static;`
2. `RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_static; hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static;`
3. `RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static;`
4. `RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_static; hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static;`
5 `RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_error; hlx_error_errors; vcl_deliver; hlx_headers_deliver`

- [ ] it's going back and forth between `hlx_type_pipeline` and `hlx_type_static`
- [ ] `hlx_type_static` does not seem to find the file it needs

**Comment by trieloff** [comment]
`wsk activation list` shows that `helix--static` never gets called.

**Comment by trieloff** [comment]
After adding more tracing: `static(/api/v1/web/trieloff/default/hlx--static?owner=trieloff&repo=helix-demo&strain=default&ref=&entry=/css/bulma.css&path=/css/bulma.css&plain=true&allow=&deny=&root=/htdocs)`

The backend URL looks reasonable.

**Comment by trieloff** [comment]
Even more when comparing with a working backend URL:

```
/api/v1/web/helix   /default/hlx--static?owner=adobe   &repo=project-helix.io&strain=default&ref=master&entry=/styles.css   &path=/styles.css   &plain=true&allow=&deny=&root=/htdocs
/api/v1/web/trieloff/default/hlx--static?owner=trieloff&repo=helix-demo      &strain=default&ref=      &entry=/css/bulma.css&path=/css/bulma.css&plain=true&allow=&deny=&root=/htdocs
```

Obvious difference: empty `ref`

**Comment by trieloff** [comment]
I fixed the empty ref, so that `curl "https://adobeioruntime.net/api/v1/web/trieloff/default/hlx--static?owner=trieloff&repo=helix-demo&strain=default&ref=master&entry=%2Fcss%2Fbulma.css&path=%2Fcss%2Fbulma.css&plain=true&allow&deny&root=%2Fhtdocs"` returns the correct response, and the `X-Trace` now looks like this (irrelevant parts omitted)

`
RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_static; hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; static(/api/v1/web/trieloff/default/hlx--static?owner=trieloff&repo=helix-demo&strain=default&ref=master&entry=/css/bulma.css&path=/css/bulma.css&plain=true&allow=&deny=&root=/htdocs); vcl_hit; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static; 
`

**Comment by trieloff** [comment]
I've disabled the redirect loop in 7f68958 which changes the response to 404:

```http
GET /css/bulma.css HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: www.primordialsoup.life
User-Agent: HTTPie/1.0.2
X-Debug: true

HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Age: 0
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 115
Content-Type: application/json
Date: Fri, 15 Mar 2019 10:30:22 GMT
Server: api-gateway/1.9.3.1
Strict-Transport-Security: max-age=31536000
Vary: X-Debug,X-Strain
Via: 1.1 varnish
X-Action-Root: /api/v1/web/trieloff/default/hlx--static
X-Backend-Name: 3l2MjGcHgWw5NUJz7OKYH3--F_AdobeRuntime
X-Backend-URL: /api/v1/web/trieloff/default/hlx--static?owner=trieloff&repo=helix-demo&strain=default&ref=master&entry=/css/bulma.css&path=/css/bulma.css&plain=true&allow=&deny=&root=/htdocs
X-CDN-Request-ID: f3739058-1fac-4fa8-a77a-323af75b1333
X-Cache: HIT
X-Cache-Hits: 1
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-FullDirname: /css
X-Github-Static-Ref: @master
X-Orig-URL: /css/bulma.css
X-Repo-Root-Path:
X-Request-ID: 5PkpHCUteHgNu0gW2UWLAaOiGwvQDEP1
X-Request-Type: Static
X-Served-By: cache-hhn1543-HHN
X-Strain: default
X-Timer: S1552645822.424901,VS0,VE452
X-Trace: vcl_recv; hlx_recv_init; hlx_strain(resolved); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(none); hlx_type_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_static(404, 0); RESTART; vcl_recv; hlx_recv_init; hlx_strain(header:default); hlx_block_recv; hlx_deny; hlx_allow; hlx_request_type(existing); hlx_type_static; hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; static(/api/v1/web/trieloff/default/hlx--static?owner=trieloff&repo=helix-demo&strain=default&ref=master&entry=/css/bulma.css&path=/css/bulma.css&plain=true&allow=&deny=&root=/htdocs); vcl_hit; vcl_deliver; hlx_headers_deliver
X-URL: /css/bulma.css
X-Version: 1065; src=1060; cli=1.0.0; rev=online; src=1060; cli=1.0.0; rev=online
X-XSS-Protection: 1; mode=block

{
    "code": "5PkpHCUteHgNu0gW2UWLAaOiGwvQDEP1",
    "error": "The requested resource does not exist."
}
```

My hypothesis is that the first 404 response from runtime (to the non-existing `css` action) gets cached, and after the restart erroneously delivered (because we use the URL as cache key, which stays the same).

I could use some input from @acme or @ejthurgo on a good course of action:

- somehow prevent the pre-restart response from getting cached?
- including `X-Request-Type` in `Vary`?

**Comment by tripodsan** [comment]
> My hypothesis is that the first 404 response from runtime (to the non-existing css action) gets cached,

this happened before with the old VLC, I added this change back then:
https://github.com/adobe/helix-cli/commit/e4341d817abc3997d7a4de203d1e2d29bd48307a

**Comment by trieloff** [comment]
I like my fix better, because it keeps the backend 404 cached, so that the backend won't get hammered on all static resources, but I'll wait for @ejthurgo's feedback.

**Comment by tripodsan** [comment]
> I like my fix better, because it keeps the backend 404 cached, so that the backend won't get hammered on all static resources

as long as it is the last request to the static action that gets cached, and not the previous ones to the main action.

**Comment by trieloff** [comment]
With `Vary: X-Request-Type`, both get cached. The 404 to the main action with `X-Request-Type=Dynamic` for 60 seconds, which will always trigger the Static fallback (just faster, because its now cached), which will be the last request in the chain and whatever the response, will get cached, too.

**Comment by tripodsan** [comment]
(I still think we should handle everything from the sam action..... this would simplify alot)
