### ISSUE TITLE
Set hlx-forwarded-host header from x-forwarded-host

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#451]
the canonical URL for everything that doesn't have a `x-cdn-url` header set is still pointing to `*.hlx.page` which is very undesirable from an SEO standpoint, meaning that helix pages can only be found in the `*.hlx.page` domain... 

i appreciate the issue we have with the `x-forwarded-host` we have with the implementation in runtime, so i think in the meantime we should set the `x-cdn-url` header with the value from `x-forwarded-host` if present in the inner CDN. this allows us to shield any other outer cdn from the implementation issues of `x-forwarded-host` in runtime.

_Originally posted by @davidnuescheler in https://github.com/adobe/helix-pages/issues/284#issuecomment-634779047_

**Comment by rofe** [comment]
Should we call it `x-hlx-host` (in reference to its predecessor `x-hlx-pages-host`)?

**Comment by trieloff** [comment]
I thought that `hlx-forwarded-host` might also work.

**Comment by trieloff** [comment]
As @rofe pointed out, the fix in #459 doesn't really fix the problem.
