### ISSUE TITLE
Header overflow

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#480]
**Description**
 We are seeing header overflow errors in helix-pages

**Comment by stefan-guggisberg** [comment]
Is Fastly reporting header overflow?

Is it the number of headers or the length of specific headers?

In case of the former, I'd prefer to keep the X-Trace if possible since it still provides valuable information in case of post mortem issue investigations.

**Comment by trieloff** [comment]
There is a chance that this pushes us over the count limit:

https://github.com/adobe/helix-pages/blob/953cad409ce9fcd109b24b64496c448372adafa7/vcl/extensions.vcl#L13-L15

**Comment by trieloff** [comment]
See #484 

```bash
$ npx mocha test/vcl-lint.js


  Lint helix.vcl
found 44 request headers
    ✓ Request header count is below limit
found 6 be request headers
    ✓ BE Request header count is below limit
found 18 response headers
    ✓ Response header count is below limit
found 14 be response headers
    ✓ BE Response header count is below limit


  4 passing (20ms)
```

looks like the number of headers is not the issue

**Comment by trieloff** [comment]
It looks like the log size may be the cause

**Comment by stefan-guggisberg** [comment]
care to elaborate?

**Comment by trieloff** [comment]
Fastly assigns limited memory to each request. This is called the workspace. Workspace is consumed by headers, ESI, and log statements. String concatenation seems to be a special area of concern.

Our traces are too verbose and exceed the workspace limit in combination with ESI.
