### ISSUE TITLE
relax path blocking for ESI

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-publish#500]
it looks like #498 should have relaxed the issues with embeds/ESIs...
somehow i am still getting the same 403 issues, see here:
https://theblog--adobe.hlx.page/en/drafts/migrated/2020/06/16/supporting-a-creative-renaissance-with-new-creative-cloud-products-and-features.html

**Comment by trieloff** [comment]
Hm. It looks like #498 has never been applied to `helix-pages`

**Comment by trieloff** [comment]
https://github.com/adobe/helix-pages/commit/3172b5a8ba5bffcc495e1a030b4550880e8d4faa didn't do anything, trying a re-deploy of `helix-publish` with https://github.com/adobe/helix-publish/commit/1176e68fd919016c76d6e1ca775973cd132e1c71

**Comment by trieloff** [comment]
🎉
