### ISSUE TITLE
browser cache being disabled because of leaked age header

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-publish#506]
**Description**
As stated by @davidnuescheler  

@trieloff and others, i just noticed that the .json requests for the query index don't get cached in my browser anymore... after looking into it, i noticed that this is probably because we send the following:
age: 13608
cache-control: max-age=7200

after flushing the inner cdn to rejuvenate the cache, the browser cache works again, with the following headers...
age: 31
cache-control: max-age=7200
New

i decided that this is an outer CDN issue, that i assigned to @trieloff https://github.com/adobe/theblog/issues/253 feel free to reassign if there is a better person to quickly fix this.

I think the fix is just to unset the resp.http.Age if an X-Debug header isn't sent in the request, then we can just unset the resp.http.Age? Forgive me if i'm assuming some knowledge here; 

https://github.com/adobe/helix-publish/blob/a8265b7e679975eea4a82a4eb1e3f769ccad9c6d/layouts/fastly/helix.vcl#L116-L130

or we can unset it here:

https://github.com/adobe/helix-publish/blob/a8265b7e679975eea4a82a4eb1e3f769ccad9c6d/layouts/fastly/helix.vcl#L372-L403

**To Reproduce**
send a curl request to a hlx.page site and look at the headers!

**Comment by trieloff** [comment]
This sounds very odd to me. Let me check with Fastly Support.

**Comment by trieloff** [comment]
Safari: uses disk cache
Firefox: makes new request 
Chrome: makes new request

**Comment by trieloff** [comment]
Possibly related: https://support.fastly.com/hc/en-us/community/posts/360040446672-Cache-Control-max-age-and-Age-headers
