### ISSUE TITLE
Provide better surrogate keys

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#569]
Purging by URL is almost impossible in Fastly because we rewrite the URL. We should have surrogate keys that enable easy purging by:

- [ ] hostname + path
- [ ] owner + repo + ref

**Comment by tripodsan** [comment]
I disagree...we should have a tool that calculates the keys.
we used the SHA, so that the header doesn't get so long. especially when multiple sources contribute to the key.

as for github, I think it is enough to include a `github` surrogate-key for all static content from github. so it can be easily be flushed from the outer CDN.

**Comment by trieloff** [comment]
For https://theblog-adobe.hlx.page/en/publish/2020/05/26/thank-you-for-your-service.html you would need to know the Sharepoint URL to calculate the surrogate key. My suggestion would be to simply add two more surrogate keys (same truncated hash) for

- https://theblog-adobe.hlx.page/en/publish/2020/05/26/thank-you-for-your-service.html
- https://github.com/adobe/theblog

Purging all of GitHub from Helix Pages is as good as purging everything.

**Comment by tripodsan** [comment]
> For https://theblog-adobe.hlx.page/en/publish/2020/05/26/thank-you-for-your-service.html you would need to know the Sharepoint URL to calculate the surrogate key. My suggestion would be to simply add two more surrogate keys (same truncated hash) for
> 
> * https://theblog-adobe.hlx.page/en/publish/2020/05/26/thank-you-for-your-service.html
ok.

> * https://github.com/adobe/theblog
but only for content actually served from github.

> Purging all of GitHub from Helix Pages is as good as purging everything.
no. only the static content (CSS and JS).

**Comment by trieloff** [comment]
I think for helix pages it would be really convenient to be able to purge an entire site for a customer

**Comment by tripodsan** [comment]
> I think for helix pages it would be really convenient to be able to purge an entire site for a customer

we're talking about the outer CDN here...so purging the entire site, is just purge all :-)

/cc @davidnuescheler WDYT?

**Comment by trieloff** [comment]
No, this is the inner cdn. the outer cdn isn't managed by helix-publish

**Comment by tripodsan** [comment]
> No, this is the inner cdn. the outer cdn isn't managed by helix-publish

yes. indirectly. since they share the surrogate-keys. I was under the assumption when talking to @davidnuescheler that we never cache on the inner CDN.

**Comment by trieloff** [comment]
https://github.com/adobe/helix-pages/issues/424 we do cache a bit
