### ISSUE TITLE
hlx publish still fails randomly

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#641]
Observed (frequently) in helix-pages CI:

```
npx hlx publish --custom-vcl='vcl/extensions.vcl' | cat
{ progress: true, level: '****', message: 'preparing fastly transaction' }
{ progress: true, level: '****', message: 'preparing service config for Helix' }
{ progress: true, level: '****', message: 'failed to set service config up for Helix' }
error: Remote publish service failed Error: 500 - "{
  "message": "Error: Response aborted",
  "stack": ["Error: Response aborted", "    at Object../node_modules/fetch-h2/dist/lib/body.js (/nodejsAction/gcxJx4lt/main.js:31789:20)", "    at __webpack_require__ (/nodejsAction/gcxJx4lt/main.js:30:30)", "    at Object../node_modules/fetch-h2/dist/index.js (/nodejsAction/gcxJx4lt/main.js:31693:16)", "    at __webpack_require__ (/nodejsAction/gcxJx4lt/main.js:30:30)", "    at Object../node_modules/@adobe/helix-fetch/src/index.js (/nodejsAction/gcxJx4lt/main.js:4510:5)", "    at __webpack_require__ (/nodejsAction/gcxJx4lt/main.js:30:30)", "    at Object../node_modules/@adobe/helix-status/src/index.js (/nodejsAction/gcxJx4lt/main.js:13136:18)", "    at __webpack_require__ (/nodejsAction/gcxJx4lt/main.js:30:30)", "    at Object../src/index.js (/nodejsAction/gcxJx4lt/main.js:67540:26)", "    at __webpack_require__ (/nodejsAction/gcxJx4lt/main.js:30:30)"],
  "status": "error"
}"
error: Error while running the Publish command: Error: Unable to setup service config
    at fetch.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:378:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) Error: Unable to setup service config
    at fetch.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:378:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error while running the Publish command
```

https://app.circleci.com/pipelines/github/adobe/helix-pages/2116/workflows/7495ac4d-f360-41e9-b513-765f72ec03b6/jobs/8343
Re-run the publish step with no code changes worked fine...

cc @trieloff

**Comment by stefan-guggisberg** [comment]
`"Error: Response aborted"` is the key hint here. This happened during the `helix-publish`<->`Fastly Endpoint` communication.

I see 2 possible scenarios:

a) the request was aborted with a timeout signal
b) a pushed stream (HTTP/2 Server Push) was aborted by the server)

AFAICS we're not using timeout signals in `helix-publish` so a) can probably be ruled out.
b) would indicate that the Fastly API Endpoint supports HTTP/2 and Server Push ...

Strange.

**Comment by stefan-guggisberg** [comment]
Just got confirmation that the Fastly API Endpoint does support HTTP/2 but doesn't use server push, so b) can be ruled out.

**Comment by stefan-guggisberg** [comment]
Here's what probably happened:

- `helix-publish` uses `fastly-native-promises` to communicate with the Fastly endpoint.
- `fastly-native-promises` uses `helix-fetch` as http client and sets a timeout (using AbortController) of 15s.
- the request to the Fastly endpoint takes longer than 15s and `helix-fetch` throws an `AbortError`.
- the `AbortError` is not handled by `fastly-native-promises` and bubbles up to `helix-publish`
- `helix-publish` treats it as a generic error and reports status `500`

**Comment by stefan-guggisberg** [comment]
https://github.com/adobe/fastly-native-promises/issues/261

**Comment by stefan-guggisberg** [comment]
Additionally, `helix-publish` should be able to detect if `fastly-native-promises` failed due to a timeout and report a status `504`.

**Comment by tripodsan** [comment]
should be better now. added more verbose output for failed strains checks.
