### ISSUE TITLE
URL of missing static resource replaced with 404 error

### ISSUE THREAD

**Issue by rofe** [adobe/helix-publish#68]
(Follow up from https://github.com/adobe/helix-cli/issues/813)

**Description**
The following HTL
```
<link rel="stylesheet" href="/i-do-not-exist.css"/>
```
will be turned into
```
<link rel="stylesheet" href='Error 404: 404: Not Found
'>
```
in production (including single quotes and line break).

**To Reproduce**
1. `hlx demo demo && cd demo`
2. Modify `src/html.htl` to reference an inexistent css file
3. `hlx` build, deploy, and publish the project
4. See error in source code

**Expected behavior**
Static URLs should remain as is, regardless of the HTTP status.

**Version:**
1.0.0

**Comment by rofe** [comment]
Looks like Fastly should set the `esi` flag for static requests

**Comment by trieloff** [comment]
Nope, it's something different.
