### ISSUE TITLE
Catch more nonsensical URLs

### ISSUE THREAD

**Issue by rofe** [adobe/helix-publish#681]
and return 403 instead of 500:
- https://blog.adobe.com/en/publish/2017/07/25/adobe-flash-update.html%gs.n7ri0q
- https://blog.adobe.com/libs/cq/analytics/templates/sitecatalyst/jcr:content.segments.json/a.1.json?datacenter=http://6.vtshd4yl3tidttqc2mbhqu2krbx2zqo.blog.adobe.com.x.bughunty.tk%23&company=xxx&username=zzz&secret=yyyy

**Comment by tripodsan** [comment]
what about switching to the #592 like @davidnuescheler suggests ?
