### ISSUE TITLE
Re-Record Polly

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#739]
@trieloff There's one test failure when building locally: **Integration Test: Test publish function locally**
(it succeeds on CI)

I am struggling with PollyJS, i.e. I need to re-record the request but I keep getting Fastly auth error (I used a valid API token). Can you have a look please?

_Originally posted by @stefan-guggisberg in https://github.com/adobe/helix-publish/issues/738#issuecomment-777615181_

**Comment by trieloff** [comment]
@stefan-guggisberg I'll take care of this next week. #738 is good to be merged.

**Comment by tripodsan** [comment]
tests are green....closing
