### ISSUE TITLE
Purge Stop through edge dictionary

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#765]
Idea: add an entry `PURGESTOP` to the `secrets` edge dictionary. If the value is `true`, refuse to purge.

**Comment by stefan-guggisberg** [comment]
The `secrets` dict can't be edited in the Fastly UI. What is the process of setting the `PURGESTOP` edge dict entry?

**Comment by trieloff** [comment]
We can use a different directory.

**Comment by davidnuescheler** [comment]
we definitely should use a different edge dict.

**Comment by rofe** [comment]
Please don't forget to document this in the runbook.
