### ISSUE TITLE
helix 2.0+ publish broken for developer.adobe.com

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-publish#77]
**Description**
Cannot `hlx publish` since helix-cli 2.0.0. Tried both 2.0.0 and 2.0.3.

You can see the failures in these two CD runs:

w/ helix-cli@2.0.0: https://circleci.com/gh/adobe/developer.adobe.com/1690
w/ helix-cli@2.0.3: https://circleci.com/gh/adobe/developer.adobe.com/1835

The error is:

```
> hlx publish

Publishing []
preparing fastly transaction 
preparing service config for Helix 
failed to set service config up for Helix
error: Remote publish service failed StatusCodeError: 500 - {"message":"FastlyError: Couldn't find Backend '{ deleted => 0000-00-00 00:00:00, name => Proxywwwadobeio3a0a, service => 0gDEZCgYFsF773b88iAgvS, version => 116 }'","stack":["FastlyError: Couldn't find Backend '{ deleted => 0000-00-00 00:00:00, name => Proxywwwadobeio3a0a, service => 0gDEZCgYFsF773b88iAgvS, version => 116 }'","
    at request.then (/nodejsAction/XXKbgecJ/node_modules/@adobe/fastly-native-promises/src/httpclient.js:100:17)","
    at process._tickCallback (internal/process/next_tick.js:68:7)"],"status":"error"}
error: Error while running the Publish command: Error: Unable to setup service config
    at request.post.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:188:13)
```

**Comment by trieloff** [comment]
@tripodsan I haven't seen the `Bad request` response, but I have seen the backend limit. One motivation to normalize the backend names was to avoid running into the backend limit.

@filmaj please try to clone your live config, delete all backends (don't activate) and then run `hlx publish` with `hlx>=2.0.0` again. 

In the meantime, I'll change the code to delete all backends called `/^Proxy.*[a-e0-9]{4}$/` that aren't on the list of backends.

**Comment by filmaj** [comment]
FYI one of the Origin Hosts in the fastly config was "example.com" 😆 

I've cloned the latest fastly service config (version 120, draft), deleted all origin hosts (which were example.com, www.adobe.io (Proxywwwadobeio861b), adobedocs.github.io (Proxyadobedocsgithubiob830), raw.githubusercontent.com (GitHub) and adobeioruntime.net (AdobeRuntime)). I didn't activate it (I don't think I can without adding an Origin Host anyways; the Activate button was greyed out).

Next I merged the greenkeeper PR to update to helix-cli@2.0.5: https://github.com/adobe/developer.adobe.com/pull/157

🤞 the CD completes!

**Comment by filmaj** [comment]
Failed with the same issue: https://circleci.com/gh/adobe/developer.adobe.com/1874

```> hlx publish

Publishing [] preparing fastly transaction 0.0sPublishing [] preparing service config for Helix 6.6sPublishing [] failed to set service config up for Helix 1.4serror: Remote publish service failed StatusCodeError: 500 - {"message":"FastlyError: Couldn't find Backend '{ deleted => 0000-00-00 00:00:00, name => Proxywwwadobeio3a0a, service => 0gDEZCgYFsF773b88iAgvS, version => 121 }'","stack":["FastlyError: Couldn't find Backend '{ deleted => 0000-00-00 00:00:00, name => Proxywwwadobeio3a0a, service => 0gDEZCgYFsF773b88iAgvS, version => 121 }'","    at request.then (/nodejsAction/XXamaOij/node_modules/@adobe/fastly-native-promises/src/httpclient.js:100:17)","    at process._tickCallback (internal/process/next_tick.js:68:7)"],"status":"error"}
error: Error while running the Publish command: Error: Unable to setup service config
    at request.post.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:188:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Unable to setup service config
Error while running the Publish command```

**Comment by filmaj** [comment]
BTW `hlx publish` didn't use the 'draft' config I created in fastly; it seems to have also cloned the latest-active config (version 119).

<img width="1342" alt="me-vs-hlx-publish" src="https://user-images.githubusercontent.com/52645/57387401-e184be80-717b-11e9-8257-8bc8b1f31c16.png">

**Comment by filmaj** [comment]
@trieloff said he would look into this tomorrow.

Relevant info:

- fastly service config name: `steveng - adobedevsite - adobedevsite.helix-demo.xyz`
- fastly service config ID: `0gDEZCgYFsF773b88iAgvS`
- it is under the Helix fastly account
- we only ever run `hlx publish` for the devsite via circleci and only off of commits to `master` branch, thus you can correlate the contents of the helix config with the output of `hlx publish` by looking at https://github.com/adobe/developer.adobe.com/blob/master/helix-config.yaml and then checking the output of the circleci run on said commit on master.

**Comment by tripodsan** [comment]
@trieloff I think the problem is, that `helix-publish` clones the last active version, and doesn't continue on the draft. so there is no way to manually prepare the version.
