### ISSUE TITLE
Support Custom VCL

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#79]
See https://github.com/adobe/helix-cli/issues/812#issuecomment-491186800

The payload should accept a new parameter `vcl`, which is an object. For each property of that object that has a corresponding file in `/layouts/fastly/${name}.vcl`, create a VCL file using the Fastly API, which is overriding the default from `/layouts/fastly/*`

**Comment by kptdobe** [comment]
To cover adobe/helix-cli#812, we only need to be able to override the newly introduced `custom.vcl` (see #85). We do not have a use yet for all the others, I would not offer the capability and wait for customer asking for it.

**Comment by kptdobe** [comment]
Custom VCL support has been introduced via the vcl https://github.com/adobe/helix-publish/blob/master/layouts/fastly/extensions.vcl. 
The publish service accepts now a `vcl` parameter and for now only support "override" is this `extensions.vcl` that can be overriden by providing the value: `{ ... "vcl": { "extensions": "your_extensions_vcl_override"}...}`

To use in a project, check https://github.com/adobe/helix-cli/issues/812.
