### ISSUE TITLE
Non GET requests do not get rejected

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#790]
https://github.com/adobe/helix-publish/blob/2950616c7afb4eda8fc43dea1018d0021a483123/layouts/fastly/helix.vcl#L1656-L1659

This code, added by @drwilco two years ago does not seem to work (anymore?) Maybe it is because we don't handle the 405 with a custom response?

**Comment by stefan-guggisberg** [comment]
It's probably a combination of https://github.com/adobe/helix-pages/commit/d787fd276026ede40ea74508dec16a815057f56a and https://github.com/adobe/helix-publish/blob/2950616c7afb4eda8fc43dea1018d0021a483123/layouts/fastly/helix.vcl#L1648-L1650

.html requests are passed, skipping the if stmt above.

@dominique-pfister
