### ISSUE TITLE
Build ESI onerror and alt support into 404 handler?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#83]
Give that we post-process most resources that could contain ESI anyway (in `helix-pipeline` or `helix-static`), it might be practical to implement support for the `alt` and `onerror` through rewritten ESI and modified VCL.

1. `<esi:include src="foo.html" alt="bar.html" />` becomes `<esi:include src="foo.html?alt=bar.html"/>`

When the 404 handler detects that this is an ESI request with an `alt` query string parameter, it will change the URL and restart the request.

2.  `<esi:include src="foo.html" onerror="continue" />` becomes `<esi include src="foo.html?onerror=continue"/>`

When the 404 handler detects that this is an ESI request with the `onerror` request parameter, it handle the request depending on the value of the `onerror` request parameter:

- `continue`: create an empty synthetic response
- `static`: create a synthetic response that contains the current URL (slightly rewritten, so recreate the required fallback for static)

In all other cases, run the standard 404 behavior.

**Comment by tripodsan** [comment]
what are the chances that fastly implements this in their ESI processing out-of-the-box?

**Comment by trieloff** [comment]
> what are the chances that fastly implements this in their ESI processing out-of-the-box?

I'd say slim, but I can check.

**Comment by kptdobe** [comment]
@trieloff any update on this ?

**Comment by kptdobe** [comment]
FYI, I followed up on the Fastly slack channel. Waiting now for ideas from @drwilco ;)
