### ISSUE TITLE
Purge should not go directly to Runtime but via Universal

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-publish#902]
See: https://github.com/adobe/helix-publish/blob/51c50a572d765e3d0cdb38ebbbc4fd7813851919/layouts/fastly/helix.vcl#L801-L812

This is required to remove the PagerDuty Runtime monitor for helix-purge (provided Universal sends all of its traffic to another serverless environment)

**Comment by trieloff** [comment]
I think this is already the case, if the action root is a Universal Runtime URL:

https://github.com/adobe/helix-publish/blob/51c50a572d765e3d0cdb38ebbbc4fd7813851919/layouts/fastly/helix.vcl#L813-L832

The `set req.backend = F_AdobeRuntime;` that @dominique-pfister pointed out is just the default.

**Comment by dominique-pfister** [comment]
Thanks, and sorry for the noise 🙏
